### ISSUE TITLE
"Supervised on Raspberry Pi with Debian 10.md" - suggest addition to sysconf.txt

### ISSUE THREAD

**Issue by tnelson32** [Kanga-Who/home-assistant#15]
to get ssh to debian to work, I also had to set root_authorized_key in sysconf.txt per: https://raspi.debian.net/defaults-and-settings/

Without it, I was able to connect but my password was not accepted

**Comment by Kanga-Who** [comment]
I'll look into this when I have some time in the coming weeks. 👍

**Comment by Tamsy** [comment]
This is true if one has followed [Installing Home Assistant Supervised on a Raspberry Pi with Debian 10](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-10/247116).

If coming from [Installing Home Assistant Supervised on Debian 10](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-debian-10/200253) the issue shouldn't happen if point 1.10 was followed:
_"Next will be **Set up users and passwords**. You will be asked to create a password for the root user. Make a note of the password you choose here, and click continue."_

As for [Installing Home Assistant Supervised on a Raspberry Pi with Debian 10](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-10/247116) instead of tampering with sysconf.txt it would be much easier to add another point to the referring instructions like i.e.:

1.5a) You will now set up a password for the root user of the system. Make a note of the password you choose. To do this, run the following command:

`passwd root`

You will be prompted to type a password for the root user and to verify the choosen password. Note that you wont see any input when doing this.

1.5b) You will now add a username and make that user part of the sudo group. To do this, run the following commands

`adduser YOUR_USERNAME`

.
.
.
